# Generated by Django 4.2.3 on 2023-09-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='descrition',
            new_name='description',
        ),
    ]
